### ISSUE TITLE
Error building the package

### ISSUE THREAD

**Issue by lightninglu10** [Minitex/react-citation#2]
Hey @chadfennell, got another issue here.

I'm trying to build the package (made a couple of changes to it) but `npm start` is giving me this error:

```

> react-citation@0.1.1 start /Users/patricklu/Q5/lunyr/citation/react-citation
> gulp dev

/Users/patricklu/Q5/lunyr/citation/react-citation/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/patricklu/Q5/lunyr/citation/react-citation/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Users/patricklu/Q5/lunyr/citation/react-citation/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/patricklu/Q5/lunyr/citation/react-citation/node_modules/react-component-gulp-tasks/tasks/release.js:1:73)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-citation@0.1.1 start: `gulp dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-citation@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patricklu/.npm/_logs/2017-08-02T21_10_16_163Z-debug.log

```

you know what's up with it? Is there another way to build?

**Comment by lightninglu10** [comment]
Deleting that line in `require-dir/index.js` fixes the issue. Seems like a bug though and not something I should be doing.

**Comment by chadfennell** [comment]
Sigh, yeah, probably ;). I on to Webpack some time ago, so what I'm thinking is that I'll just migrate this component to webpack  - maybe later today.

**Comment by lightninglu10** [comment]
Closing as not planned: this 2017 build error is no longer actionable on current versions, and the repo has seen no pushes in years. If it still reproduces, please re-open with fresh details.
